### ISSUE TITLE
OutPut html error

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/rubocop-sketchup#104]
## Expected behavior

No such file or directory @ rb_sysopen - C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-sketchup-0.4.0/assets/output.html.erb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-sketchup-0.4.0/lib/rubocop/sketchup/formatter/extension_review.rb:61:in `read'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-sketchup-0.4.0/lib/rubocop/sketchup/formatter/extension_review.rb:61:in `render_html'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-sketchup-0.4.0/lib/rubocop/sketchup/formatter/extension_review.rb:55:in `finished'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/formatter/formatter_set.rb:32:in `block (3 levels) in <class:FormatterSet>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/formatter/formatter_set.rb:32:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/formatter/formatter_set.rb:32:in `block (2 levels) in <class:FormatterSet>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/runner.rb:70:in `inspect_files'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/runner.rb:39:in `run'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/cli.rb:157:in `execute_runner'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/cli.rb:85:in `execute_runners'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/lib/rubocop/cli.rb:41:in `run'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/exe/rubocop:13:in `block in <top (required)>'
C:/Ruby22-x64/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rubocop-0.58.1/exe/rubocop:12:in `<top (required)>'
C:/Ruby22-x64/bin/rubocop:23:in `load'
C:/Ruby22-x64/bin/rubocop:23:in `<main>'
Finished in 11.294787361999624 seconds

## Steps to reproduce the problem
rubocop -d -f extension_review -o D:/report.html

## RuboCop version
0.58.1 (using Parser 2.5.1.0, running on ruby 2.2.4 x64-mingw32)

## RuboCop SketchUp version
"0.4.0"

![image](https://user-images.githubusercontent.com/28385638/51590678-c15f2580-1f25-11e9-9245-8e8da6b781c9.png)

**Comment by thomthom** [comment]
Can you try with the latest 0.6.0 release?

**Comment by thomthom** [comment]
I think this was fixed for version 0.5.0 in this commit: https://github.com/SketchUp/rubocop-sketchup/commit/b9cbb854b719b0049d6c0f1c2ced24c3b29179ef

**Comment by LItterBoy-GB** [comment]
@thomthom  I try it.  Thank you.
