### ISSUE TITLE
SketchupRequirements/SketchupExtension fails with error

### ISSUE THREAD

**Issue by thomthom** [SketchUp/rubocop-sketchup#51]
https://github.com/bbatsov/rubocop/issues/5656#issuecomment-374161571

I keep running into errors with node matcher.

The latest case is a snippet like this:

```ruby
module Example
  msg = "Hello World"
  msg += "Foo Bar"
end
```

A matcher like this:

```ruby
        def_node_search :sketchup_extension_new, <<-PATTERN
          ({:lvasgn :ivasgn :cvasgn :gvasgn :casgn} ...
            (:send
              (:const nil? :SketchupExtension) :new
              _
              _))
        PATTERN
```

Inspection like this:

```ruby
def investigate(processed_source)
  source_node = processed_source.ast
  extension_nodes = sketchup_extension_new(source_node).to_a
  # ...
end
```

Which leads to error like this:

```
  1) RuboCop::Cop::SketchupRequirements::SketchupExtension Default source path does not throw an error when inspecting source
     Failure/Error: extension_nodes = sketchup_extension_new(source_node).to_a

     NoMethodError:
       undefined method `type' for :msg:Symbol
     # C:3:in `block in sketchup_extension_new'
     # C:2:in `sketchup_extension_new'
     # ./lib/rubocop/sketchup/requirements/sketchup_extension.rb:44:in `each'
     # ./lib/rubocop/sketchup/requirements/sketchup_extension.rb:44:in `to_a'
     # ./lib/rubocop/sketchup/requirements/sketchup_extension.rb:44:in `investigate'
     # ./spec/rubocop/sketchup/requirements/sketchup_extension_spec.rb:93:in `block (3 levels) in <top (required)>'
```

My spec to reproduce:

```ruby
    it 'does not throw an error when inspecting source' do
      inspect_source(['module Example',
                      '  msg = "Hello World"',
                      '  msg += "Foo Bar"',
                      'end'],
                      './src/hello.rb')
      expect(cop.offenses.size).to eq(1)
    end
```

Any ideas? (I get lost when I try to debug into the matchers.)

**Comment by thomthom** [comment]
Opened a PR with possible fix: https://github.com/bbatsov/rubocop/pull/5714
